
create table if not exists sock (

    id          biginteger generated by default as identity primary key,
    color       varchar(10) not null,
    cottonPart  integer check(cotton_part >= 0 AND cotton_part  <= 100) not null,
    quantity    integer check(quantity >= 0) not null

    );

GO
